### ISSUE TITLE
[FEAT][tabular] Improve feature importance

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1218]
**Is your feature request related to a problem? Please describe.**
There are a few problems with the existing feature importance mechanism:

1. Error messages are not clear enough when FI can't be computed (there is at least one documented case of a user getting only the error [here](https://github.com/deepchecks/deepchecks/blob/9630d75a1e81ebf29483fb219eb4e06dd3956f54/deepchecks/utils/features.py#L184) ). It is also not clear what are the implications of not succeeding to compute FI. 
2. When models don't have built in FI, the alternative default permutation importance method takes a long time to run and can't be skipped. The parameter limiting this (feature_importance_timeout) is not documented outside of the context source code.
3. Not clear how get_model_of_pipeline works when features the pipeline uses are not the same as the ones used by the model (e.g. Encoding).

**Describe the solution you'd like**

- [ ] Improve the error messages and explain the usage of FI in the package.
- [ ] Document how to limit FI computation time / how to skip
- [ ] Check that FI works for a pipeline (and add tests)

**Comment by shir22** [comment]
Current warning that makes feature importance time unknown
(and after updating -> this  is also a good place to document how to control this
btw - why are there two warnings, is this the desired behavior or a bug?  (note that they popped up at different times)

![image (25)](https://user-images.githubusercontent.com/33841818/162333619-c1687975-4ced-4e43-8105-70475b32af0f.png)
)

**Comment by nirhutnik** [comment]
### DoD:
Approved solution by Shir&Bressler, implemented in main

### Tasks:
* Error messages - 
** Add bar for calculation of FI. Add message that says this can be skipped using the "timeout" parameter. 1 SP
** Have a more descriptive message that explains what's wrong, and how the user can fix this - 0 SP
* Documentation - add a page(?) of documentation for FI in deepchecks, its usage, and how to skip / configure. - 2 SP

**Comment by nirhutnik** [comment]
Taking the pipeline issue into a new task - https://github.com/deepchecks/deepchecks/issues/1268
