### ISSUE TITLE
[FEAT][Tabular] Improve understandability of Single Feature Contribution

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1399]
- [ ] Consider a different name
- [ ] Try to improve clarity of output (reconsider the pink "diff" line)
- [ ] Add the single dataset version to integrity suite (make sure again it's OK).

**Comment by nirhutnik** [comment]
### Inputs:
Add new input to diff condition - "change_direction", that gets "all" (default), "train-to-test", "test-to-train". 
"all" means we look at absolute value. The others mean what the mean.

### Tasks:
1. Change condition to be on absolute diff as default, but enable user to change that - 0.5 SP
2. Add to integrity suite - 0 SP
3. Plot: - 1.5 SP
Change to this:
![image](https://user-images.githubusercontent.com/92314933/167632611-6867913e-9fc9-41f5-8fdc-88497e9c34fb.png)
https://stackoverflow.com/questions/67221226/how-to-add-difference-in-percentage-above-bars-in-plotly

**Comment by nirhutnik** [comment]
### Inputs:
Add new input to diff condition - "change_direction", that gets "all" (default), "train-to-test", "test-to-train". 
"all" means we look at absolute value. The others mean what the mean.

### Tasks:
1. Change condition to be on absolute diff as default, but enable user to change that - 0.5 SP
2. Add to integrity suite - 0 SP
3. Plot: - 1.5 SP
Change to this:
![image](https://user-images.githubusercontent.com/92314933/167632611-6867913e-9fc9-41f5-8fdc-88497e9c34fb.png)
https://stackoverflow.com/questions/67221226/how-to-add-difference-in-percentage-above-bars-in-plotly

**Comment by noamzbr** [comment]
Suggestion - instead of change in %, display the change in absolute PPS units.

**Comment by nirhutnik** [comment]
Agree and that was what I meant to do

**Comment by noamzbr** [comment]
Partially addressed by #1478
