### ISSUE TITLE
[DOCS][CV] Add property user guide

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#954]
Properties are a central theme in the current checks of the vision package. We need to:
- [x] Rename label measurements to properties - resolved by #1013 
- [x] Refactor label properties to work by batch and not by single label - resolved by #1013 
- [x] Improve image properties names - resolved by #1013 
- [ ] Create a dedicated user guide to help the user use them and define custom properties. 
- [ ] Link checks using properties to the user guide.
